/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,jsx,ts,tsx}',
        './components/**/*.{js,jsx,ts,tsx}',
        './features/**/*.{js,jsx,ts,tsx}',
        '../../packages/widgets/**/*.{js,jsx,ts,tsx}',
        '../../packages/native-modules/**/*.{js,jsx,ts,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                background: 'var(--color-bg-base)',
                'background-alt': 'var(--color-bg-alt)',
                card: 'var(--color-bg-card)',
                border: 'var(--color-border)',
                text: 'var(--color-text)',
                'text-light': 'var(--color-text-light)',
                'text-muted': 'var(--color-text-muted)',
                'text-primary': 'var(--color-text-primary)',
                'text-secondary': 'var(--color-text-secondary)',
                primary: 'var(--color-primary)',
                'primary-light': 'var(--color-primary-light)',
                'primary-lighter': 'var(--color-primary-lighter)',
                'primary-dark': 'var(--color-primary-dark)',
                success: 'var(--color-success)',
                'success-bg': 'var(--color-success-bg)',
                'success-text': 'var(--color-success-text)',
                'success-border': 'var(--color-success-border)',
                warning: 'var(--color-warning)',
                'warning-bg': 'var(--color-warning-bg)',
                'warning-text': 'var(--color-warning-text)',
                'warning-border': 'var(--color-warning-border)',
                error: 'var(--color-error)',
                'error-bg': 'var(--color-error-bg)',
                'error-text': 'var(--color-error-text)',
                'error-border': 'var(--color-error-border)',
                premium: 'var(--color-premium)',
                'premium-dark': 'var(--color-premium-dark)',
                info: 'var(--color-info)',
                'info-light': 'var(--color-info-light)',
                'info-bg': 'var(--color-info-bg)',
                'info-text': 'var(--color-info-text)',
                'info-border': 'var(--color-info-border)',
                admin: 'var(--color-admin)',
            },
            borderRadius: {
                sm: 'var(--radius-sm)',
                md: 'var(--radius-md)',
                lg: 'var(--radius-lg)',
            },
        },
    },
    plugins: [],
};
