import {
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconBell,
  IconBook,
  IconBug,
  IconBuilding,
  IconBuildingWarehouse,
  IconCalendar,
  IconCalendarEvent,
  IconCamera,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconClock,
  IconClockHour3,
  IconCloud,
  IconCloudBolt,
  IconCloudFog,
  IconCloudOff,
  IconCloudRain,
  IconCloudSnow,
  IconCloudStorm,
  IconCloudUpload,
  IconCrown,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDna,
  IconDroplets,
  IconEye,
  IconEyeOff,
  IconFence,
  IconFileText,
  IconFlask2,
  IconGift,
  IconGitBranch,
  IconHeart,
  IconHelpCircle,
  IconHome,
  IconLayoutGridAdd,
  IconLeaf,
  IconLock,
  IconMail,
  IconMapPin,
  IconMoon,
  IconPackage,
  IconPackageExport,
  IconPencil,
  IconPhoto,
  IconPlant2,
  IconPlus,
  IconPower,
  IconRefresh,
  IconRuler,
  IconScanEye,
  IconScissors,
  IconSearch,
  IconSettings,
  IconShield,
  IconShieldExclamation,
  IconSparkles,
  IconSun,
  IconSunHigh,
  IconTags,
  IconTemperature,
  IconTornado,
  IconTrash,
  IconTrees,
  IconUserCircle,
  IconUsers,
  IconWind,
  IconWorld,
  IconX,
  type Icon,
  type IconProps,
} from '@tabler/icons-react-native';

/** Global visual defaults for every application icon. */
export const ICON_DEFAULTS = {
  size: 24,
  strokeWidth: 1.75,
} as const;

export type AppIconProps = IconProps;

function createAppIcon(SourceIcon: Icon) {
  function AppIcon({
    size = ICON_DEFAULTS.size,
    strokeWidth = ICON_DEFAULTS.strokeWidth,
    ...props
  }: AppIconProps) {
    return <SourceIcon size={size} strokeWidth={strokeWidth} {...props} />;
  }

  AppIcon.displayName = `AppIcon(${SourceIcon.displayName ?? 'TablerIcon'})`;
  return AppIcon;
}

/**
 * Canonical icon registry. Keys are stable app-level IDs; Tabler names stay
 * private to this module so the icon set and defaults can be changed centrally.
 */
export const ICONS = {
  AlertTriangle: createAppIcon(IconAlertTriangle),
  ArrowLeft: createAppIcon(IconArrowLeft),
  ArrowRight: createAppIcon(IconArrowRight),
  Bell: createAppIcon(IconBell),
  BookOpen: createAppIcon(IconBook),
  Bug: createAppIcon(IconBug),
  Building2: createAppIcon(IconBuilding),
  Calendar: createAppIcon(IconCalendar),
  CalendarDays: createAppIcon(IconCalendarEvent),
  Camera: createAppIcon(IconCamera),
  Check: createAppIcon(IconCheck),
  CheckCircle: createAppIcon(IconCircleCheck),
  ChevronDown: createAppIcon(IconChevronDown),
  ChevronLeft: createAppIcon(IconChevronLeft),
  ChevronRight: createAppIcon(IconChevronRight),
  ChevronUp: createAppIcon(IconChevronUp),
  Clock: createAppIcon(IconClock),
  Clock3: createAppIcon(IconClockHour3),
  Cloud: createAppIcon(IconCloud),
  CloudDrizzle: createAppIcon(IconCloudRain),
  CloudFog: createAppIcon(IconCloudFog),
  CloudHail: createAppIcon(IconCloudSnow),
  CloudLightning: createAppIcon(IconCloudBolt),
  CloudOff: createAppIcon(IconCloudOff),
  CloudRain: createAppIcon(IconCloudRain),
  CloudRainWind: createAppIcon(IconCloudStorm),
  CloudSun: createAppIcon(IconSunHigh),
  CloudUpload: createAppIcon(IconCloudUpload),
  Cloudy: createAppIcon(IconCloud),
  Crown: createAppIcon(IconCrown),
  Dna: createAppIcon(IconDna),
  Droplets: createAppIcon(IconDroplets),
  Eye: createAppIcon(IconEye),
  EyeOff: createAppIcon(IconEyeOff),
  Fence: createAppIcon(IconFence),
  FileText: createAppIcon(IconFileText),
  FlaskConical: createAppIcon(IconFlask2),
  Gift: createAppIcon(IconGift),
  GitBranch: createAppIcon(IconGitBranch),
  Globe: createAppIcon(IconWorld),
  Grid2X2Plus: createAppIcon(IconLayoutGridAdd),
  Heart: createAppIcon(IconHeart),
  HelpCircle: createAppIcon(IconHelpCircle),
  Home: createAppIcon(IconHome),
  Image: createAppIcon(IconPhoto),
  Leaf: createAppIcon(IconLeaf),
  Lock: createAppIcon(IconLock),
  Mail: createAppIcon(IconMail),
  MapPin: createAppIcon(IconMapPin),
  Monitor: createAppIcon(IconDeviceDesktop),
  Moon: createAppIcon(IconMoon),
  Package: createAppIcon(IconPackage),
  PackageCheck: createAppIcon(IconPackageExport),
  Pencil: createAppIcon(IconPencil),
  Plus: createAppIcon(IconPlus),
  Power: createAppIcon(IconPower),
  RefreshCw: createAppIcon(IconRefresh),
  Ruler: createAppIcon(IconRuler),
  Save: createAppIcon(IconDeviceFloppy),
  ScanSearch: createAppIcon(IconScanEye),
  Scissors: createAppIcon(IconScissors),
  Search: createAppIcon(IconSearch),
  Settings: createAppIcon(IconSettings),
  Shield: createAppIcon(IconShield),
  ShieldAlert: createAppIcon(IconShieldExclamation),
  SlidersHorizontal: createAppIcon(IconAdjustmentsHorizontal),
  Sparkles: createAppIcon(IconSparkles),
  Sprout: createAppIcon(IconPlant2),
  Sun: createAppIcon(IconSun),
  Tags: createAppIcon(IconTags),
  Thermometer: createAppIcon(IconTemperature),
  Tornado: createAppIcon(IconTornado),
  Trash2: createAppIcon(IconTrash),
  Trees: createAppIcon(IconTrees),
  UserRound: createAppIcon(IconUserCircle),
  Users: createAppIcon(IconUsers),
  Warehouse: createAppIcon(IconBuildingWarehouse),
  Wind: createAppIcon(IconWind),
  X: createAppIcon(IconX),
} as const;

export type IconId = keyof typeof ICONS;

export const {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Bug,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Clock3,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSun,
  CloudUpload,
  Cloudy,
  Crown,
  Dna,
  Droplets,
  Eye,
  EyeOff,
  Fence,
  FileText,
  FlaskConical,
  Gift,
  GitBranch,
  Globe,
  Grid2X2Plus,
  Heart,
  HelpCircle,
  Home,
  Image,
  Leaf,
  Lock,
  Mail,
  MapPin,
  Monitor,
  Moon,
  Package,
  PackageCheck,
  Pencil,
  Plus,
  Power,
  RefreshCw,
  Ruler,
  Save,
  ScanSearch,
  Scissors,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Sun,
  Tags,
  Thermometer,
  Tornado,
  Trash2,
  Trees,
  UserRound,
  Users,
  Warehouse,
  Wind,
  X,
} = ICONS;
