import type { PlantI18nLocaleRow } from './types';

// This file is generated by scripts/build-plant-i18n.js
// Edit packages/convex/convex/data/plantI18nSource/*.json instead.
export const plantI18nPtSeedData: PlantI18nLocaleRow[] = [];
